ENTITY_GENRE: dict[str, str] = {
    "action": "боевик",
    "western": "вестерн",
    "gangster": "гангстер",
    "detective": "детектив",
    "drama": "драма",
    "historical": "исторический",
    "comedy": "комедия",
    "music_comedy": "музыкальная комедия",
    "melodrama": "мелодрама",
    "noir": "нуар",
    "adventure": "приключенческий",
    "fairytale": "сказка",
    "tragedy": "трагедия",
    "thriller": "триллер",
    "fantastic": "фантастика",
    "fantasy": "фентези",
    "disaster": "катастрофа",
    "horror": "ужас",
}
